update readme for standardsettings 2.0
KingContaria/StandardSettings pull request #16
Opened 2024-08-12 09:30 UTC by maskersss

closes #13

2024-08-12 09:35 UTC, maskersss commented
i removed the global standardoptions part as i assumed it wasn't implemented, let me know if i'm wrong

2024-08-12 09:42 UTC, KingContaria commented
it was implemented just not documented anywhere, you have to put a the redirect into .minecraft/config/mcsr/standardsettings.global

2024-08-12 09:48 UTC, KingContaria requested changes
Could you explain F3 Pause on World Load and its delay on first world setting too?

2024-08-12 09:48 UTC, KingContaria commented on README.md
> +To get to the config screen, go to `Options > Book and Quill > StandardSettings` in game. Here you can edit  all the settings changed by StandardSettings, including most settings from Minecraft's `op
> some unnecessary options (for example multiplayer related) are also left out

Pretty sure it just covers every option now.

2024-08-12 10:11 UTC, maskersss commented
please fact check the "How can I use a global standardoptions file?" part

2024-08-12 22:28 UTC, KingContaria approved these changes

2024-08-13 19:44 UTC, merged

2024-08-13 19:45 UTC, KingContaria commented
ty :)